# Generated by Django 4.2.2 on 2023-06-28 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='Affiliate',
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='website',
            field=models.URLField(default='#'),
        ),
    ]
